android.dependency.useConstraints=true
android.enableJetifier=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.useAndroidX=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.parallel=true
